export const sagaActions = {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_ADMIN: 'LOGIN_USER_ADMIN',
  LOGOUT_USER: 'LOGOUT_USER',
  REGISTER_USER: 'REGISTER_USER',
};

export const uiActions = {
  SHOW_SPINNER: 'SHOW_SPINNER',
};

export const companiesActions = {
  UPDATE_FAVOURITE_COMPANIES: 'UPDATE_FAVOURITE_COMPANIES',
};
